theme:
  name: material
  palette:
    primary: teal
    accent: teal
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/BodenmillerGroup/IMCWorkflow
repo_name: BodenmillerGroup/IMCWorkflow

use_directory_urls: false

site_name: Primer to IMC analysis
nav:
    - Home: index.md
    - Introduction: intro.md
    - Pre-processing: prepro.md
    - Viewers: viewers.md
    - Analysis: analysis.md
    
markdown_extensions:
    - footnotes
