theme:
  name: material
  palette:
    primary: teal
    accent: teal
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/BodenmillerGroup/IMCWorkflow
repo_name: BodenmillerGroup/IMCWorkflow

use_directory_urls: false

site_name: Primer to IMC analysis
nav:
    - Home: index.md
    - Introduction: intro.md
    - Image processing: process.md
    - Image visualization: viewers.md
    - Downstream analysis: analysis.md
    
markdown_extensions:
    - footnotes
    - attr_list
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg