---
title: "Read in Data"
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

```{r}
library(SingleCellExperiment)
```

```{r}
cells.mat <- read.csv("data/extdata/cells.csv", stringsAsFactors = FALSE)
image.mat <- read.csv("data/extdata/image.csv", stringsAsFactors = FALSE)
relationships.mat <- read.delim("data/extdata/Object_relationships.txt", stringsAsFactors = FALSE)
panel.mat <- read.csv("data/extdata/panel.csv", stringsAsFactors = FALSE)


image_number <- cells.mat$ImageNumber # check if this exists
cell_number <- cells.mat$ObjectNumber # check if this exists
cur_cells <- cells.mat[,grepl("Intensity_MeanIntensity_", colnames(cells.mat))]
other_features <- cells.mat[,!grepl("Intensity_MeanIntensity_", colnames(cells.mat)) & 
                                !colnames(cells.mat) %in% c("ImageNumber", "ObjectNumber")]
  

panel.channels <- paste0("c", 1:nrow(panel.mat))
cells.channels <- gsub(".*_", "", colnames(cur_cells))
    
cur_cells <- cur_cells[,match(panel.channels, cells.channels)]
  # Build the SingleCellExperiment object
sce <- SingleCellExperiment::SingleCellExperiment(assays = list(counts=t(cur_cells)))
  
  # Build the row metadata
  row.data <- DataFrame(row.names = colnames(cur_cells),
                        panel.mat)
  
  # Build the column metadata
  col.data <- DataFrame(row.names = rownames(cur_cells),
                        image_number = image_number,
                        cell_number = cell_number,
                        other_features)
  
  # Add these metadata to SCE object
  colData(sce) <- col.data
  rowData(sce) <- row.data  

saveRDS(sce, "data/extdata/sce.rds")
```